### ISSUE TITLE
IDE Static attribute checking shows warning

### ISSUE THREAD

**Issue by episodeyang** [smarie/python-autoclass#5]
@smarie Not sure if there is a way around this: In IDE (I'm using pyCharm), when using `autoargs` the class attribute shows up as undefined during the static checking of the IDE. It looks like this:

![screenshot 2017-09-04 05 58 34](https://user-images.githubusercontent.com/630490/30023740-4baf1422-9136-11e7-9ebb-12d2c4399074.png)

It would be great if there is a way to get around this issue.

**Comment by episodeyang** [comment]
Besides preserving the `__init__` function call signature, it would be great if the class could be used as a namespace with good IDE autocompletion/autosuggestion for the attributes.

Is this possible?

**Comment by smarie** [comment]
I am confirm both issues. Not sure it was always the case with older versions of Pycharm. I need to investigate further.

**Comment by smarie** [comment]
Issue was created in PyCharm issue tracker: https://youtrack.jetbrains.com/issue/PY-26029

**Comment by smarie** [comment]
There is not much we can do on this side apart from voting for the pycharm issue. Closing.
